---
topic:
  request:  request-queue
  reply:    reply-queue

---
kafka:
  bootstrapAddress: localhost:9092

---
logging:
  level:
    org.springframework: ERROR
    se.cambio.cosmic.cm.graph: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: app.log